name: 'Merged branches cleaner'
description: 'Removes all the branches that were already merged'
author: 'Miguel Angel Moreno Regalado'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  ignore_branches:
    description: 'Protect those branches that you dont want to be deleted'
runs:
  using: 'node16'
  main: 'dist/index.js'
