name: 'GitHub Branch Cleaner'
description: 'Deletes merged branches and inactive branches in a GitHub repository'
author: 'Miguel Moreno mmorenoregalado@gmail.com'

inputs:
  base_branches:
    description: 'Base branches separated by commas'
    required: true
  days_old_threshold:
    description: 'Age threshold in days to delete inactive branches'
    required: true
    default: '7'

runs:
  using: 'composite'
  steps:
    - name: 'Configure Git'
      shell: 'bash'
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: 'Delete branches'
      shell: 'bash'
      run: |
        ./entrypoint.sh "${{ inputs.base_branches }}" "${{ inputs.days_old_threshold }}" "${{ inputs.token }}"
