name: Clean Up Branches

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:

jobs:
  cleanup_branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Branch Cleaner
        uses: ./
        with:
          base_branches: 'main'
          days_old_threshold: 1
          token: ${{ secrets.GITHUB_TOKEN }}
